# .github/workflows/Sync_to_gitee.yml

name: Sync to remote gitee

on: 
  push:
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/Yunuuuu/jade.git"
          source_branch: "master"
          destination_repo: "git@gitee.com:yunyunp/jade.git"
          destination_branch: "master"
          destination_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
